name: EridiumEconomy
version: '${project.version}'
main: at.mtxframe.eridiumeconomy.EridiumEconomy
api-version: '1.21'
load: POSTWORLD
author: MeteryX
depend: [MtxFrame]


commands:
  jobs:
    description: Opens the job Gui
    usage: /jobs
    aliases:
      - berufe
  jobminer:
    description: opens a miner job menu
    usage: /jobminer
    aliases:
      - miner
  jobfarmer:
    description: opens a farmer job menu
    aliases:
      - farmer
  jobhunter:
    description: opens a hunter job menu
    aliases:
      - hunter
  jobwoodcutter:
    description: opens a woodcutter job menu
    aliases:
      - woodcutter
  jobfisher:
    description: opens a fisher job menu
    aliases:
      - fisher
  pay:
    description: lets a player pay money to another player
    aliases:
      - zahlen
  backpack:
    description: lets a player open a backpack
    aliases:
      - rucksack